GRID_SIZE = 3
HAYWARD_LAT = 37.6688
HAYWARD_LON = -122.0808
ZOOM_LEVEL = 0.5
MY_REGION = [HAYWARD_LON - ZOOM_LEVEL, HAYWARD_LON + ZOOM_LEVEL, HAYWARD_LAT - ZOOM_LEVEL, HAYWARD_LAT + ZOOM_LEVEL]
OUTPUT_DIR = "Stroke-Triage-Policy-Project Updated/PlottingFiles/grid_plot_csvs_CA"